### ISSUE TITLE
Error installing 5.3.0.2 plugin on ES 5.3

### ISSUE THREAD

**Issue by ajes15** [jprante/elasticsearch-langdetect#61]
Hi,

While trying to install the plugin it is throwing the following error,

./elasticsearch-plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/5.3.0.2/elasticsearch-langdetect-5.3.0.2-plugin.zip
-> Downloading http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/5.3.0.2/elasticsearch-langdetect-5.3.0.2-plugin.zip
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 503 for URL: http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/5.3.0.2/elasticsearch-langdetect-5.3.0.2-plugin.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.io.IOException: Server returned HTTP response code: 503 for URL: http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/5.3.0.2/elasticsearch-langdetect-5.3.0.2-plugin.zip

I have tried with 5.3.0.0 plugin and it gives me the same error.

Could you please help with the issue?

**Comment by jprante** [comment]
Server xbib.org is up and well, no errors.

Try Maven Central mirror:

http://repo1.maven.org/maven2/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/5.3.0.2/elasticsearch-langdetect-5.3.0.2-plugin.zip

**Comment by ajes15** [comment]
Thanks a lot.
The Maven Central mirror worked!
